### ISSUE TITLE
Dota Plus Chat Wheel bug

### ISSUE THREAD

**Issue by Wondermarin** [jeffhill/Dota2#204] opened 2022-06-02 20:16 UTC
### Description

Arcana's rarity items do not affect the voice chat wheel, the voice acting remains standard.
While the persona affects the voice acting.

**Comment by NMOTH** [comment] 2022-06-02 20:18
this is duplicate of #93 , please close this

**Closed** 2022-06-03 06:56 UTC

**Comment by prasedenica** [comment] 2022-09-06 07:43
Thanks for this great topic. Hope you will contribute more to the forum
[duck life](https://ducklife.online)
