### ISSUE TITLE
Ability Draft: Rearm shard still grants March of the Machines, instead of Warp Flare

### ISSUE THREAD

**Issue by Bu3nyy** [jeffhill/Dota2#723] opened 2022-06-08 07:26 UTC
### Description

Rearm still grants your hero March of the Machines when you acquire Aghanim's Shard, instead of granting Warp Flare.

**Comment by RGBKnights** [comment] 2022-06-08 14:56
A duplicate of #36 please close.

**Closed** 2022-06-08 22:40 UTC
