### ISSUE TITLE
Blood Mist pierces BKB inconsistently

### ISSUE THREAD

**Issue by wilddrop** [jeffhill/Dota2#386] opened 2022-06-03 12:56 UTC
Blood Mist is magic damage both for self & enemy damage now, but pierces BKB only on the self damage.

https://user-images.githubusercontent.com/26395431/171858001-bf507cdb-fc25-4756-824c-98139ab14a63.mp4

**Comment by wilddrop** [comment] 2022-06-03 13:17
> 

I agree this is probably why it's occuring, and it's completely possible that it's intended!  If that's confirmed, this can be closed.  Right now it's inconsistent and potentially an oversight/bug.

**Comment by NMOTH** [comment] 2022-06-03 16:15
as @TheZett said, bkb doesnt provide magic resistance. BKB doesn't make you immune to your own self casted spells.
This is not a bug. Please close this.

**Closed** 2022-06-05 10:17 UTC
