### ISSUE TITLE
Morph on puck

### ISSUE THREAD

**Issue by Lifewillbeok** [jeffhill/Dota2#209] opened 2022-06-02 20:23 UTC
### Ability name

Morph

### Description

when you use Morp on a puck the skills are not on those button
![Screenshot_1](https://user-images.githubusercontent.com/106772811/171731218-d0059221-13ee-4605-9d9e-9c842c29f9c3.png)
![Screenshot_3](https://user-images.githubusercontent.com/106772811/171731230-67c9b925-9bae-4162-b60b-6c475a460809.png)
s

### Example Match ID (and possibly Timestamp)

every game

**Comment by Lifewillbeok** [comment] 2022-06-02 20:23
fixed

**Comment by xm** [comment] 2022-06-02 20:26
This is a duplicate of #3

**Closed** 2022-06-02 20:27 UTC
