### ISSUE TITLE
Dota TV not working

### ISSUE THREAD

**Issue by Ibacca** [jeffhill/Dota2#1067] opened 2022-06-11 01:20 UTC
### Description

If I try to watch any live game on Dota TV it just gets stuck on watch game status "waiting to watch game". Then after some time it states "could not watch this game at this time". This has been this way since patch. 

### Example Match ID (and possibly Timestamp)

Any Dota TV game

### Screenshots

![image](https://user-images.githubusercontent.com/107287504/173167129-76dfe7e8-c6e7-43c9-b711-db8525d12c25.png)

![image](https://user-images.githubusercontent.com/107287504/173167122-3bc2bd65-4adf-4e9c-82f4-5dbda91171a1.png)

**Comment by sidhantchadda** [comment] 2022-06-11 03:39
I'm also experiencing this issue at the moment looks like there are some recent reddit posts with the same issue as well.

https://www.reddit.com/r/DotA2/comments/v9ow0t/what_is_wrong_with_live_games_i_cant_watch_them/

https://www.reddit.com/r/DotA2/comments/v9oat5/cant_watch_games_on_new_computer/

**Comment by sidhantchadda** [comment] 2022-06-11 03:42
Looks like there is another issue filed: https://github.com/jeffhill/Dota2/issues/1059

**Comment by unkndld** [comment] 2022-06-11 07:52
Same here, been experiencing this since 7.31d

**Comment by alexkosj** [comment] 2022-06-11 09:42
> Same here, been experiencing this since 7.31d
+1

**Comment by Aluerie** [comment] 2022-06-11 11:57
duplicate of #923 (with more upvotes/comments as well) so please close issue + upvote/comment that one.

**Comment by Ibacca** [comment] 2022-06-11 16:18
closing issue. duplicate of #923

**Closed** 2022-06-11 16:18 UTC
