### ISSUE TITLE
Snapfire Level 15 talent Missing in Ability Draft

### ISSUE THREAD

**Issue by BlochOli** [jeffhill/Dota2#439] opened 2022-06-03 18:40 UTC
### Description

The level 15 talent on Snapfire for +2 Lil' Shredder shots is missing (right side) even if you have drafted Lil' Shredder, Gives 500 gold instead.

### Example Match ID (and possibly Timestamp)

6600131900

**Comment by BenjinZA** [comment] 2022-06-03 18:44
Ability specific talents are changed to gold talents in ability draft. This is intended behaviour.

**Comment by BlochOli** [comment] 2022-06-03 18:46
> Ability specific talents are changed to gold talents in ability draft. This is intended behaviour.

Not if you have picked the ability. Don't you think I would have reported the level 20 and 25 talents being missing as well if that was the case?

**Comment by NMOTH** [comment] 2022-06-03 18:54
this is duplicate of #71 issue is already mentioned

**Comment by BlochOli** [comment] 2022-06-03 18:57
> this is duplicate of #46 issue is already mentioned, mind closing this? if you have further notes and questions add them to #46

Oh I see, I did a quick check for duplicates but couldn't have known from the title alone that it was reported already.

**Closed** 2022-06-03 18:57 UTC
