### ISSUE TITLE
Windranger Focus Fire Disjoint

### ISSUE THREAD

**Issue by Smelsert** [jeffhill/Dota2#225] opened 2022-06-02 21:13 UTC
### Ability name

Focus Fire

### Description

https://streamable.com/3o3ze6 (disappearing)

https://streamable.com/wo5wpi (losing vision)

When the target under Windranger's Focus Fire disappears and appears again, or Windranger loses vision of the Focus Fired target, Windranger seems to stop Focus Firing until any (new non-attack-something-else) command is issued. This used to not happen and wasn't put in any change logs as far as I can tell.

With Manta Style, it seems to be inconsistent (sometimes she Focus Fires immediately, sometimes she does not).

If you look carefully at Windranger's animation while she's in this "stuck" state, it seems she's trying to attack, but can't. Compare her animation [here](https://streamable.com/wwmpp1) before and after she loses the Focus Fire buff.

### Example Match ID (and possibly Timestamp)

I tested this in demo mode and attached videos.

**Comment by Aluerie** [comment] 2022-06-02 21:15
Sorry, but it is duplicate of #21

you probably better close your issue, upvote+copypaste comment in that issue instead

**Closed** 2022-06-02 21:20 UTC
