### ISSUE TITLE
Outdated interface

### ISSUE THREAD

**Issue by faddeefde** [jeffhill/Dota2#590] opened 2022-06-05 09:00 UTC
### Description

The panel for displaying information about the hero is outdated. 

There are no neutral items, tps, shard and aghanim's scepter here. Also, it is impossible to view the quick buy of an ally. And it also closes when you click on the "select hero" button to return the camera to your hero.

I know that few people use this setting, but the champion of the recent Major Taiga uses it and he has to turn off this option in the middle of the game to see the full information.

### Screenshots

![interface bug](https://user-images.githubusercontent.com/106907199/172043017-72de4cba-12ea-41c7-9628-6aa7acb4b068.png)
![taiga](https://user-images.githubusercontent.com/106907199/172043265-9021517a-cc2f-4775-986e-dce6e60aa221.jpg)

**Comment by Aluerie** [comment] 2022-06-05 09:59
Duplicate of #135, #333, #471 ; 

It's better to upvote+comment existing issues instead of making duplicates per jeffhill ;

**Comment by faddeefde** [comment] 2022-06-05 10:30
oh, okay, thanks

**Closed** 2022-06-05 10:34 UTC
