### ISSUE TITLE
Pango ulti and Roll up getting canceled by Fissure, Ice shard and Cogs

### ISSUE THREAD

**Issue by LokeLok** [jeffhill/Dota2#17] opened 2022-06-02 16:50 UTC
ES https://streamable.com/d0pnsa 
Tusk https://streamable.com/bdmsxd
Clock https://streamable.com/1vm1rh

**Comment by nandavelugoti** [comment] 2022-06-03 19:14
I couldn't reproduce Tusk's interaction shown in the video. In my case, Pango just bounces off the shard in the opposite direction (just like hitting a structure/wall). Any comment on this?

**Comment by LokeLok** [comment] 2022-06-03 19:44
It is the hardest one to reproduce, it has to hit on a certain angle on the front of the shard(also can happen inside the shard on the front). It should be easy to reproduce while hes in Roll Up, since Pango is standing still.

**Comment by TommyHuang-dev** [comment] 2022-06-03 23:07
If you turn on free abilities and spam ice shards its much easier, very hard to do with just one shard

**Comment by jeffhill** [comment] 2022-06-16 21:39
This will be fixed in the hotfix today.

There was a weird interaction with pathing blockers who had the DOTA_OBSTRUCTION_PROPERTY_NPC_STOPPER flag set and Pago's Ult, where if Pangolier tried to "bounce off" an obstruction, but couldn't find a clear space behind him to bounce to, Roll Up would stop. The new behavior is to continue rolling, so if a fissure or something appears under you while rolling and you cannot "bounce", you'll just continue forward until you're clear of the fissure.

**Closed by jeffhill** 2022-06-16 21:39 UTC

**Comment by LokeLok** [comment] 2022-06-17 03:16
I played around in demo after the update, Rolling Thunder is fixed. Roll Up still get canceled by Fissure, Ice Shard and Power Cogs. Any reason why it wouldn't get affected by this fix?
