### ISSUE TITLE
QOL: There should be an audible and/or visual indicator that the courier was unable to deliver all of your items due to a lack of space.

### ISSUE THREAD

**Issue by Big-Mudd** [jeffhill/Dota2#81] opened 2022-06-02 17:38 UTC
This would be especially helpful for supports who often find themselves 9 slotted with consumables early in the game. By the time the player notices the issue, the courier may have already traveled a great distance back towards the fountain.

**Comment by viology** [comment] 2022-06-02 23:32
Not a bug, and there already is a visual indicator: a number over the courier icon will always show how many items it is currently holding.

**Comment by Big-Mudd** [comment] 2022-06-02 23:38
I know it's not a bug. That's why I prefaced it as a QOL suggestion. Also if the courier behaves the same whether all items were delivered or not, then that's not an indicator that all items couldn't be delivered. You can also tell that some items were not delivered by looking at your inventory.....the point is something should seek to grab your attention when it occurs.

**Comment by Daar543** [comment] 2022-06-03 15:46
Regarding the item delivery (inventory/backpack/courier), items which cannot be assembled should be prioritized by gold, e.g. I get delivered +10 agility item into backpack and +6 agility item into inventory.

**Comment by NMOTH** [comment] 2022-06-03 16:55
> Regarding the item delivery (inventory/backpack/courier), items which cannot be assembled should be prioritized by gold, e.g. I often get delivered +10 agility item into backpack and +6 agility item into inventory, when it should better be the other way around.

that can backfire when you are having regen and an item delivered. Also if as a support I have wards + more expensive item delivered, I want the wards to be usable right away. Prioritizing by gold doesn't work. as a nulls does much more than an ogre axe,  yes is nearly half the price.  Having boots + staff delivered on the spot when you are running away from enemy, if it puts boots in your bag you might die. If boots are equipped right away you can get more distance and even kill the enemy etc. 
Not a good thing to implement.

**Comment by Big-Mudd** [comment] 2022-06-03 17:19
> > Regarding the item delivery (inventory/backpack/courier), items which cannot be assembled should be prioritized by gold, e.g. I often get delivered +10 agility item into backpack and +6 agility item into inventory, when it should better be the other way around.
> 
> that can backfire when you are having regen and an item delivered. Also if as a support I have wards + more expensive item delivered, I want the wards to be usable right away. Prioritizing by gold doesn't work. as a nulls does much more than an ogre axe, yes is nearly half the price. Having boots + staff delivered on the spot when you are running away from enemy, if it puts boots in your bag you might die. If boots are equipped right away you can get more distance and even kill the enemy etc. Not a good thing to implement.

An alternative system I've thought about is to prioritize items that will be combined with others that are already in the inventory, since that would instantly create space for the rest of the items on the courier. However, I can imagine that being problematic if an item can be combined with multiple inventory items, and seems maybe overly complicated in general, so I didn't suggest it. Just theorizing here as a fun aside.

**Comment by Daar543** [comment] 2022-06-03 22:49
> > > Regarding the item delivery (inventory/backpack/courier), items which cannot be assembled should be prioritized by gold, e.g. I often get delivered +10 agility item into backpack and +6 agility item into inventory, when it should better be the other way around.
> > 
> > 
> > that can backfire when you are having regen and an item delivered. Also if as a support I have wards + more expensive item delivered, I want the wards to be usable right away. Prioritizing by gold doesn't work. as a nulls does much more than an ogre axe, yes is nearly half the price. Having boots + staff delivered on the spot when you are running away from enemy, if it puts boots in your bag you might die. If boots are equipped right away you can get more distance and even kill the enemy etc. Not a good thing to implement.
> 
> An alternative system I've thought about is to prioritize items that will be combined with others that are already in the inventory, since that would instantly create space for the rest of the items on the courier. However, I can imagine that being problematic if an item can be combined with multiple inventory items, and seems maybe overly complicated in general, so I didn't suggest it. Just theorizing here as a fun aside.

That already exists, all items which can be combined are already combined. Exception is aghanim's shard, which can be consumed instantly, yet is not prioritized (already an issue on that).

**Comment by karlww** [comment] 2022-06-15 16:00
> I know it's not a bug. That's why I prefaced it as a QOL suggestion.

This is explicitly a bug tracker. If you know your idea is not a bug the solution isn't to ignore that fact and tag it "QOL," it's to not submit it at all.

**Comment by Big-Mudd** [comment] 2022-06-15 16:47
> > I know it's not a bug. That's why I prefaced it as a QOL suggestion.
> 
> This is explicitly a bug tracker. If you know your idea is not a bug the solution isn't to ignore that fact and tag it "QOL," it's to not submit it at all.

Well I posted two other QOL improvements and both have already been fixed by Valve devs including JeffHill. Maybe you should message him to let him know he's not using his tracker properly.

**Comment by Aluerie** [comment] 2022-06-15 19:58
@RealLarwood per [JeffHill](https://www.reddit.com/r/DotA2/comments/v5zdu1/this_suggestion_seemed_quite_divisive_on_github/ibe2nit/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3)4tg paragraph - it's completely fine with him for us to post QoL requests. And indeed, some nice ones were already implemented from this bugtracker. So you shouldn't downvote issues *just because* they are QoL suggestions.

**Comment by jeffhill** [comment] 2022-06-16 20:47
This will be in the hotfix later today. Thanks for the QoL suggestion!

**Closed by jeffhill** 2022-06-16 20:47 UTC
