### ISSUE TITLE
Casting Spell Steal on Vengeful Spirit Aghs Illusion Steals Nothing but Puts Spell Steal on Cooldown

### ISSUE THREAD

**Issue by CarltheCat47** [jeffhill/Dota2#106] opened 2022-06-02 17:49 UTC
This problem does not exist with other illusions where it just won't let you cast spell steal.

**Comment by TheZett** [comment] 2022-06-02 18:06
This is technically the intended behaviour that Spell Steal used to use until early 6.86 for all illusions.

It currently being a 'free illusion detector' is the bug, not that you can use it on an illusion and it goes on cooldown without giving you a spell.

Spell Steal is supposed to go on cooldown and not give you a spell when targeting any illusion.

**Comment by NMOTH** [comment] 2022-06-03 19:56
mind closing this.
 @TheZett explained why this is intended behavior and not a bug

**Closed** 2022-06-03 20:50 UTC
