### ISSUE TITLE
[ UI ] Favorite hero closes match history

### ISSUE THREAD

**Issue by Sunshinecxz** [jeffhill/Dota2#450] opened 2022-06-03 19:50 UTC
### Description

Favorite hero closes match history in profile and other information, may move them right a little? 

### Screenshots

![image](https://user-images.githubusercontent.com/106839813/171939333-1df3b82b-7535-409a-abf3-b927591c1075.png)
![image](https://user-images.githubusercontent.com/106839813/171939420-bd3be0dc-33bf-46be-a9ee-122d41f4cabe.png)

**Comment by NMOTH** [comment] 2022-06-03 19:51
This is a duplicate of #384  please close

**Closed** 2022-06-03 19:54 UTC
