### ISSUE TITLE
Random BKBs, smokes, lingering spells/ultimates in Spectator mode

### ISSUE THREAD

**Issue by arkhanov** [jeffhill/Dota2#250] opened 2022-06-02 22:19 UTC
And sometimes while rewinding/ff ing there's a huge burst of sound, please mute or lower the volume for that. Thanks Jeff!

**Comment by NMOTH** [comment] 2022-06-02 22:21
this is a duplicate of #53

**Comment by arkhanov** [comment] 2022-06-02 23:03
> this is a duplicate of #53

the other 2 points aren't fixed though

**Closed** 2022-06-02 23:28 UTC
