### ISSUE TITLE
Windranger ultimate stop hitting the target when it comes out of fog

### ISSUE THREAD

**Issue by Lyralei27** [jeffhill/Dota2#170] opened 2022-06-02 19:28 UTC
### Description

Back in the days, windranger's ultimate used to have a fix target, wich means, once you ulti someone you couldn't stop hitting him while walking, only if you hold position you would stop hitting, but if you move you'll start hitting again. It was a big problem because blade mail used to ignore BKB. They changed it, and now you can press stop then move and you'll not hit the in-range-enemy while walking. 
Thats the back ground, the problem now is, I think that this change also changed her ultimate interaction with fog, because now, if the enemy enters the fog windranger will not hit him when it comes out. It might seems not a big deal, but it is, because it broke her biggest power spike that used to be diving T1 at lvl 6, and since windranger core fades out late game it was a HUGE nerff. 
It was not mentioned at any patch so I believe to be what seems a small interation bug. And what reinforce it is that if you stop (without clicking the stop hotkey, only right clicking) and move again she will start hitting as you can see on the video. 
As I said, it might seems small if don't play windranger mid, but it made her ultimate uselles since she is now played consistently only as support.

https://user-images.githubusercontent.com/106769496/171721973-f1bf5de4-d338-49b1-a9a4-dc5662ad268a.mp4

**Comment by Aluerie** [comment] 2022-06-02 20:28
This is duplicate of #21 

You probably better close your issue and upvote+copypaste your comment with video there

**Closed** 2022-06-16 22:03 UTC
