### ISSUE TITLE
Item sets are not grouped together

### ISSUE THREAD

**Issue by ArtemPikul** [jeffhill/Dota2#601] opened 2022-06-05 13:25 UTC
### Description

Some of the hero item sets are not grouped together into one set, and thus cannot be equipped instantly by choosing a set from a hero loadout. Example on screenshot is only one of many: equipped set is "Demon's Bacchanal", howewer there is no option for it under "Full sets" tab.

### Screenshots

![image](https://user-images.githubusercontent.com/16233703/172052738-f567443e-627e-4dd2-94c1-d0772c47a9b8.png)

**Comment by hydrazines** [comment] 2022-06-05 17:24
Thanks for adding this. I believe this is a duplicate of #259; could you add this example to that thread and close this one? Thanks!

**Closed** 2022-06-10 15:52 UTC
