### ISSUE TITLE
Enigma immortal Effect Selection fix pls  : (

### ISSUE THREAD

**Issue by FlyEnigma** [jeffhill/Dota2#858] opened 2022-06-09 01:05 UTC
### Cosmetic Item Name

World Chasm artifact 

### Description

There's no option for blackhole immortal effect of enigma

### Example Match ID

-

### Screenshots

![20220609040212_1](https://user-images.githubusercontent.com/107159418/172742434-3291cb2a-f91d-44cd-88d5-d65af90e6f24.jpg)

**Comment by theTrolleyProblem** [comment] 2022-06-09 03:29
duplicate of #849 
please look up your issue before creating a new one. it would help with development to prevent duplicates.

**Closed** 2022-06-10 10:55 UTC
