### ISSUE TITLE
hoodwink ult issue

### ISSUE THREAD

**Issue by Eastofeden1** [jeffhill/Dota2#413] opened 2022-06-03 15:04 UTC
### Ability name

sharpshooter

### Description

if u use sharpshooter and try to use some spell which need your hero to turn around to opposite direction from that you are aiming to, so your hero will freeze until your ult not auto shot, and you can not even move and shot by yourself

### Example Match ID (and possibly Timestamp)

i have no any moments

**Comment by NMOTH** [comment] 2022-06-03 15:46
This is duplicate of #32 please close this and add further comments on #32

**Closed** 2022-06-03 15:54 UTC
