### ISSUE TITLE
Morphling talent tree

### ISSUE THREAD

**Issue by JamesTorillo** [jeffhill/Dota2#722] opened 2022-06-08 06:50 UTC
### Description

Unexpected string concat with level 10 and 25 talent name (**+[!s:value]**)

### Screenshots

![image](https://user-images.githubusercontent.com/99023653/172550547-6943040a-07ab-42b1-ac56-3d5c98f88c04.png)

**Comment by anonymo0se** [comment] 2022-06-08 06:55
duplicate of #92

**Closed** 2022-06-08 16:57 UTC
