### ISSUE TITLE
Holy Locket is not amplifying Dawnbreaker heal from Luminosity

### ISSUE THREAD

**Issue by spiersonfrontrow** [jeffhill/Dota2#1510] opened 2022-06-23 09:24 UTC
### Item name

Holy Locket

### Description

The amount healed by Dawnbreaker and allies from a Luminosity crit is the same before and after equipping a Holy Locket.

Tested in demo mode and in a co-op bot game (linked)

### Example Match ID and Timestamp

6631101400 - 16:00-18:00

**Comment by LokeLok** [comment] 2022-06-23 13:15
Intended behavior, the heal from Luminosity gets amp from any lifesteal amp sources(e.g sange, s&y etc) and not Holy Locket.

**Comment by spiersonfrontrow** [comment] 2022-06-25 12:12
> Intended behavior, the heal from Luminosity gets amp from any lifesteal amp sources(e.g sange, s&y etc) and not Holy Locket.

I tested this, and the heal numbers don't increase from equipping either Sange or Paladin Sword (versus raw damage of the same amount)

**Comment by LokeLok** [comment] 2022-06-25 13:12
I also did some testing and you're correct that Sange and Paladin Sword are not increasing any heal. I think you should close this thread and open a new one, with lifesteal amp not working on Luminosity.

**Closed** 2022-06-25 13:18 UTC
