### ISSUE TITLE
[Visual Bug] Misaligned account level

### ISSUE THREAD

**Issue by kostakis** [jeffhill/Dota2#542] opened 2022-06-04 09:50 UTC
### Description

Open dota 2
Go to your profile
Go to trophies section
The level of the main trophy is not centered

Resolution: 1920 x 1080
Exclusive full-screen
Ratio: 16:9
Laptop: Lenovo legion 5 15ach6h, 15.6" screen size

### Screenshots

![image](https://user-images.githubusercontent.com/44324384/171994086-9a53c52b-91ce-4bb2-9145-98768baf1d8d.png)

**Comment by Awoocado** [comment] 2022-06-04 19:26
duplicate of #331

**Closed** 2022-06-04 21:00 UTC
