### ISSUE TITLE
Dota UI - Hero HUD | Unit query panel

### ISSUE THREAD

**Issue by deathkiller1** [jeffhill/Dota2#473] opened 2022-06-03 21:39 UTC
### Description

Bug : When you click on an ally/enemy hero, there is a small panel that pops up on the right. This panel doesn't contain the TP and neutral item slot. 

This is the reason many players avoid using this panel.
I'm talking about this : Options > Interface (on your right) > Unit query overrides Hero Panel.

### Example Match ID (and possibly Timestamp)

NA

### Screenshots

https://dev.dota2.com/forum/dota-2/user-interfaces/hero-hud/258256-unit-query-window-issues

For now just add the TP and neutral item slot. Later on you can review additional enchantments to that hud.

**Comment by Aluerie** [comment] 2022-06-04 00:26
Duplicate of #135, #333, #471 ; 

Oh well ; just use search bar next time before posting and upvote/leave comments in already made issues instead of duplicating

**Comment by deathkiller1** [comment] 2022-06-04 09:06
Closing because it's a duplicate

**Closed** 2022-06-04 09:05 UTC
