### ISSUE TITLE
Bane: Casting Nightmare on an ally who then dies gives Bane an assist

### ISSUE THREAD

**Issue by singuillary** [jeffhill/Dota2#246] opened 2022-06-02 22:16 UTC
### Ability name

Nightmare

### Description

Sometimes it can be beneficial for Bane to Nightmare an ally to take advantage of the short immunity period. I have done this many times, and have noticed that sometimes if the ally dies in spite of my efforts my assists go up by 1 in the K/D/A tracker. This has happened in many of my games, but I have linked just one of my matches below. At one point during a match a while ago, I had a total combined kills and assists that exceeded the total kill count of my team. As far as I can tell, the bug does not happen when Nightmaring yourself. In the posted Match ID, the Dire kill the Wraith King shortly after I nightmare him to try to dodge the killing blow. My assist count goes up by 1 (despite the Radiant having no kills, no suicides either).

### Example Match ID (and possibly Timestamp)

6597458612 - 02:10

**Comment by Memoframe** [comment] 2022-06-03 00:40
You got assist but gold was from last-hitting a creep.

**Comment by NMOTH** [comment] 2022-06-03 01:37
> Ah, you are correct. Edited the post to reflect that. It used to give gold but it seems they fixed that part at least.

please close this ticket. ty

**Closed** 2022-06-03 01:43 UTC

**Comment by ZzZombo** [comment] 2022-06-03 16:27
@NMOTH:

> please close this ticket. ty

On what ground did you request it? As far as I see, only the gold portion was edited out, the assist portion of the report still stands and unless it's debunked I fail to see why should the report be closed. Also can you please explain your affiliation with Jeff? You're very active requesting changes and demanding action, but to me it looks like backseat moderating, and not good one while at that.

**Comment by NMOTH** [comment] 2022-06-03 16:44
> @NMOTH:
> 
> > please close this ticket. ty
> 
> On what ground did you request it? As far as I see, only the gold portion was edited out, the assist portion of the report still stands and unless it's debunked I fail to see why should the report be closed. Also can you please explain your affiliation with Jeff? You're very active requesting changes and demanding action, but to me it looks like backseat moderating, and not good one while at that.

commented on the wrong thread, chill.

**Comment by Memoframe** [comment] 2022-06-03 16:57
> > @NMOTH:
> > > please close this ticket. ty
> > 
> > 
> > On what ground did you request it? As far as I see, only the gold portion was edited out, the assist portion of the report still stands and unless it's debunked I fail to see why should the report be closed. Also can you please explain your affiliation with Jeff? You're very active requesting changes and demanding action, but to me it looks like backseat moderating, and not good one while at that.
> 
> commented on the wrong thread, chill.

What about other questions he asked? I'm kinda curious too. No offence.

**Comment by NMOTH** [comment] 2022-06-03 17:08
> > > @NMOTH:
> > > > please close this ticket. ty
> > > 
> > > 
> > > On what ground did you request it? As far as I see, only the gold portion was edited out, the assist portion of the report still stands and unless it's debunked I fail to see why should the report be closed. Also can you please explain your affiliation with Jeff? You're very active requesting changes and demanding action, but to me it looks like backseat moderating, and not good one while at that.
> > 
> > 
> > commented on the wrong thread, chill.
> 
> What about other questions he asked? I'm kinda curious too. No offence.

it is recommended you state one issue in one ticket ( unless it is multiple instances of similar issues). 
Otherwise it becomes difficult to keep track of things.
There was a response to his gold question, if he feels the assist portion is not answered he can make a new ticket.
To add to it, same thing happens with oracle , gets assists when allies die under his spell killed by enemies. I believe this is perhaps intended and not a bug. As you do not get any gold or xp for the assist even if the counter goes up. 

It really isn't game breaking. Cause technically you are assisting enemy in getting your ally killed 😂

**Comment by Memoframe** [comment] 2022-06-03 17:16
> > > > @NMOTH:
> > > > > please close this ticket. ty
> > > > 
> > > > 
> > > > On what ground did you request it? As far as I see, only the gold portion was edited out, the assist portion of the report still stands and unless it's debunked I fail to see why should the report be closed. Also can you please explain your affiliation with Jeff? You're very active requesting changes and demanding action, but to me it looks like backseat moderating, and not good one while at that.
> > > 
> > > 
> > > commented on the wrong thread, chill.
> > 
> > 
> > What about other questions he asked? I'm kinda curious too. No offence.
> 
> it is recommended you state one issue in one ticket ( unless it is multiple instances of similar issues). Otherwise it becomes difficult to keep track of things. There was a response to his gold question, if he feels the assist portion is not answered he can make a new ticket. To add to it, same thing happens with oracle , gets assists when allies die under his spell killed by enemies. I believe this is perhaps intended and not a bug. As you do not get any gold or xp for the assist even if the counter goes up.
> 
> It really isn't game breaking. Cause technically you are assisting enemy in getting your ally killed 😂

Under "other questions" I meant who are you :D
