### ISSUE TITLE
IO Tether cannot be leveled when he is actively Tethered 

### ISSUE THREAD

**Issue by Fi-eMan** [jeffhill/Dota2#602] opened 2022-06-05 13:34 UTC
### Ability name

Tether

### Description

Io cannot level up Tether while he is actively tethered. This is inconsistent with things like medusa shield that can be leveled while active. IO must break Tether to level it up

### Example Match ID (and possibly Timestamp)

any match

**Comment by TheZett** [comment] 2022-06-05 19:00
This is caused by Break Tether only having 1 level.

Most sub-spells have the same amount of levels as their main spells and are linked to another, so leveling one automatically levels the other one as well.

This should get fixed by making Break Tether having 4 levels as well, additionally Break Tether should show Tether’s stats as well, so you dont have to untether to see how Tether scales when leveled up.

**Comment by Naaveen-Kumar** [comment] 2022-06-05 20:13
> This is caused by Break Tether only having 1 level.
> 
> Most sub-spells have the same amount of levels as their main spells and are linked to another, so leveling one automatically levels the other one as well.
> 
> This should get fixed by making Break Tether having 4 levels as well, additionally Break Tether should show Tether’s stats as well, so you dont have to untether to see how Tether scales when leveled up.

Oh you are that arc warden spammer

**Comment by TheZett** [comment] 2022-06-06 08:51
> Oh you are that arc warden spammer

Less of a spammer and more of a caretaker regarding the hero’s bugs.

**Comment by jeffhill** [comment] 2022-06-20 21:07
This will be fixed in the hotfix later today. Thank you for the bug report, and thank you for the suggestion for the fix, @TheZett!

**Closed by jeffhill** 2022-06-20 21:07 UTC
