### ISSUE TITLE
Sven's Immortal Bug

### ISSUE THREAD

**Issue by CYAXARES-76** [jeffhill/Dota2#375] opened 2022-06-03 11:39 UTC
### Cosmetic Item Name

Vigil Signet

### Description

Vigil Signet was missing in Sven's Hero Portrait. 

### Example Match ID

No

### Screenshots

![Uploading Sven.jpg…]()

**Comment by CYAXARES-76** [comment] 2022-06-03 11:39
![Sven](https://user-images.githubusercontent.com/106813672/171846689-bc77e30f-8897-4db1-98a3-b101990db8f2.jpg)

**Comment by SnabrielSnarsch** [comment] 2022-06-03 15:17
i think this is intentional, otherwise it will block most of the portrait

**Comment by CYAXARES-76** [comment] 2022-06-03 15:30
> i think this is intentional, otherwise it will block most of the portrait

![image](https://user-images.githubusercontent.com/106813672/171885117-2dddbebd-8907-4362-828f-659105256915.png)
It doesn't block that much

**Comment by NMOTH** [comment] 2022-06-03 15:49
This is intentional, not a bug.
Please close this. thanks

**Closed** 2022-06-03 16:00 UTC
