### ISSUE TITLE
razor link bug

### ISSUE THREAD

**Issue by PosiTr0n505** [jeffhill/Dota2#1108] opened 2022-06-11 18:06 UTC
### Ability name

Static link + soulbind

### Description

Razor static link when used with Grimstroke's soulbind will not start stealing the damage from the two targets, but only from the secondary target (the target you didn't press the link on)

https://user-images.githubusercontent.com/107320276/173199755-4c29f470-e81b-4d66-abac-747eecdd4038.mp4

### Example Match ID (and possibly Timestamp)

if the video was uploaded, it's a 10 second clear video of the bug

**Comment by InappropriatePenguin** [comment] 2022-06-11 18:28
This is a duplicate of #292. Can you close this issue and upvote that one?

**Closed** 2022-06-11 22:19 UTC
