### ISSUE TITLE
After the June 8 update, game started feeling silly. Feels like packet loss even tho fps 144, ping 40 and packet loss 0

### ISSUE THREAD

**Issue by Krev5** [jeffhill/Dota2#1065] opened 2022-06-11 00:55 UTC
### Description

Other people have already confirmed it here.
https://www.reddit.com/r/DotA2/comments/v8986m/with_todays_update_i_started_feeling_lower/
Trying to get it to the devs if possible.

**Comment by eddeT** [comment] 2022-06-11 07:40
Duplicate of an existing issue: https://github.com/jeffhill/Dota2/issues/915

Please close this one to avoid cluttering.

**Closed** 2022-06-11 07:41 UTC
