### ISSUE TITLE
Please make VAC Ban of 'Overwolf' application 

### ISSUE THREAD

**Issue by terran5151** [jeffhill/Dota2#559] opened 2022-06-04 17:09 UTC
### Description

Here is the program: https://go.overwolf.com/dotaplus/

Please make this application a bannable offense, people use this app in order to see the enemy teams last picks and most played heroes so that they can ban those heroes, this ruins the game, the enemy team should have no information other than what is in the client, this gives an unfair advantage to those that use this application.

Also, if one person likes to spam one hero, they are not able to do so while people use this application as the other team can just ban their hero that they ENJOY playing, this makes the person's game sad, it is allowed to spam a hero if you want but people who have overwolf can ruin that.

**Comment by uzsibox** [comment] 2022-06-04 17:40
It uses the api to pull PUBLICLY AVAILABLE DATA. You can set in game to be anonymus.

**Comment by terran5151** [comment] 2022-06-04 18:13
> It uses the api to pull PUBLICLY AVAILABLE DATA. You can set in game to be anonymus.

Except it put's all of that data straight in front of your face as the game is beginning? Isn't that like an unfair advantage that isn't already in the game by it's self? Shouldn't valve control what apps are used with their games?

If a game is starting, who is going to open dotabuff and check everyones profiles to see what heroes they have picked recently and their most played heroes? No one is going to do that, right? And that is publicly available data.

Then comes Overwolf, that just puts all of the data straight in front of your face as the game begins, that is an unfair advantage.

**Comment by yavuzhanglr** [comment] 2022-06-04 18:41
This is not a bug.

**Comment by Memoframe** [comment] 2022-06-04 18:56
It can be solved only by shutting down API which means RIP dotabuff, opendota etc or adding these features in game (and it will not be for free :D).
Both solutions sux imo.

**Comment by wersonit** [comment] 2022-06-04 19:46
This app is actually helpful. Because there are people who play in party (usually 2-3) and they pick the same heroes every game, and it's much harder to play against them like that. But if you ban their heroes, then it's almost always a free win. In my opinion them having 1 hero pool is their own problem. I'm not saying I'm 100% right, but this is how I see it.

**Comment by TheZett** [comment] 2022-06-04 19:59
> This is not a bug.

It is technically cheating, as you’re using a 3rd party application to give you an unfair advantage during the draft, and the drafting phase is part of the game.

**Comment by Memoframe** [comment] 2022-06-04 20:22
3rd party is cheating? Ok.
When you use dotabuff you are cheating, because you can see heroes winrates and pick heroes with higher winrate, and it's not present in dota. Every new patch you just chose best heroes and win more.
When you watch dota guides on youtube you are cheating, because people there give you insight info you do not have in dota.
You use advices you can never come to by yourself in result winning more.
Thousands of other services out there.
You are cheater, accept it.

**Comment by uzsibox** [comment] 2022-06-04 21:35
> > This is not a bug.
> 
> It is technically cheating, as you’re using a 3rd party application to give you an unfair advantage during the draft, and the drafting phase is part of the game.
> 
> Valve also removed the ability to view the match history of non-friends from within the client when they moved from Source1 to Source2, something that overwolf allows. Being able to see the match history of random people is not supposed to be a thing. Overwolf is by definition cheating and circumventing restrictions that were intentionally imposed onto the client.

Not everybody only plays one hero my friend <3

**Comment by TheZett** [comment] 2022-06-04 22:44
> 3rd party is cheating? Ok. When you use dotabuff you are cheating, because you can see heroes winrates and pick heroes with higher winrate, and it's not present in dota. Every new patch you just chose best heroes and win more. When you watch dota guides on youtube you are cheating, because people there give you insight info you do not have in dota. You use advices you can never come to by yourself in result winning more. Thousands of other services out there. You are cheater, accept it.

dotabuff does not automatically analyse all 9 other player’s profiles, their last 1000 matches and suggest bans for each player within 3 seconds.

Overwolf trivialises the drafting phase by providing you with information you’re not supposed to obtain within the short 10 second ban phase of the drafting phase. It is effectively cheating during the draft and thus should be VAC restricted.

Nice attempt at a strawman though, your logic does not check out though.

@uzsibox my in-game versatility is 9.4/10, so your shitty attempt at a spiteful comment failed.
Shame on your for defending cheaters and the scum at Overwolf who forced people to either set their profile to private, and thus prevent them from using stats pages, or get cheated against by overwolf using cheaters.

**Comment by anko** [comment] 2022-06-04 23:10
I think a good solution would be to treat players as anonymous during the pick stage in matchmaking games, such that their player ID isn't transmitted to other players' game clients until the pick stage finishes.

This would prevent players' public histories from being used against them during the pick. People could still use the API normally otherwise, and custom lobbies would be excluded so tournament organisers can still implement custom pick screens.

**Comment by Memoframe** [comment] 2022-06-04 23:39
Dotabuff trivializes your personal analysis of statistics.
Guides/streams trivializes your personal analysis of game as a whole: which heroes work well together, which items better in which situation etc.
These two make more harm than overwolf.

**Comment by MateriaX99** [comment] 2022-06-05 00:54
Overwolf is more impactful short term, because the data is presented to you directly in the drafting phase every game against the other team being targeted negatively from it.

Dotabuff statistics and Guides don't have immediate impact as you need to make changes to yourself based on their inputs. 

See difference? 1 is impacting another group of person immediately on a negative way every game (that I call cheating), while the latter depends on you improving yourself, which will impact others.

**Comment by Memoframe** [comment] 2022-06-05 01:18
You can't understand that dotabuff and overwolf are same shit but for different things?
They are both automated tools to process info.
They are both 3rd party.
They are both instantly shows you info which you can't gather by hand so quickly.
They are both cheats by your definition.
Is this immidiate possiblity to ban one hero or understanding drafts/itemizing etc as a whole it does not matter.
You are too focused on one thing and do not see anything else.
Such threads should go to reddit, not into BUG report system.

**Comment by OraCLesofFire** [comment] 2022-06-05 01:37
Regarding an actual solution that could be presented. Keeping the player ID server side until they have picked in the draft could be a simple solution that avoids this issue.

**Comment by terran5151** [comment] 2022-06-05 07:46
> It uses the api to pull PUBLICLY AVAILABLE DATA. You can set in game to be anonymus.

And all of your past matches are still stored in dotabuff profile if you had one before which means again, they see all your most played heroes which they can ban...

**Comment by hektor36** [comment] 2022-06-05 16:23
if you run a private server to parse matchdata as they are being played , you can still get the "anonymous" account data. but most sites big enough get a cease and desist revealing hidden data.

**Comment by AzimsTech** [comment] 2022-06-05 20:49
Just to add to the conversation, It is impossible to be completely anonymous unless you make a new account. This encourages smurfing.

**Comment by frozoff** [comment] 2022-06-06 15:54
Please add what was suggested above:
anonymous mode for banning/picking phase so we can open our profiles for dotabuff statistics. It got worse when owerwolf was introduced for dota

**Comment by Crimento** [comment] 2022-06-08 04:26
I would remove hiding match data altogether, IMO players with hero puddles have worse impact on game experience than someone banning your favourite hero. Why is this an issue?

**Comment by MissPotato** [comment] 2022-06-08 04:31
I would like to add that Overwolf is used for legitimate things unrelated to DotA. Even if it was decided that the overwolf plugin was cheating, blanket VAC banning anyone who uses overwolf would be a lot of false positives.

**Comment by Varpie** [comment] 2022-06-08 06:43
While I like the suggestion to make user data anonymous during the draft phase, I would like to point out that it should only affect external data, as it is important for players to recognize who they play with/against.

Unlike third-party programs that give you data you normally wouldn't have access to, recognizing other players gives you an input based on your own experience, so it cannot possibly be considered cheating.  
And knowing who you play with is essential, because without that, all games would basically have the same draft phase, especially for supports who pick first: ban the same heroes, pick your favorite heroes. It does not invite synergy with your teammates, nor can you counter-pick preemptively. Those are a skill on their own.

**Comment by xdugyx** [comment] 2022-06-09 04:57
There is no need to VAC ban the overwolf app.

All you have to do is stop writing the player IDs to the server_log.txt file in the folder SteamLibrary\steamapps\common\dota 2 beta\game\dota

It gathers the player IDs through that file. Whenever you accept a match the Dota client writes the Match ID and all player IDs into that file

**Comment by GodXeria** [comment] 2022-06-11 08:57
I didn't know half of Dota players use overwolf, I thought always it's a cheat and that only scum of the earth would use it to ruin other people's games, but seeing how some people defend it with flawed logic and stupid ass takes, makes me sad and less eager to start a new Dota match now..

**Comment by AncientsAndAntiques** [comment] 2022-06-11 13:50
> Perhaps a good solution would be to treat players as anonymous during the pick stage in matchmaking games? So that their player ID isn't transmitted to other players' game clients until the pick stage finishes?
I have been waiting for this change for years. At _very least_ in Unranked.

**Comment by ChrisG683** [comment] 2022-06-11 15:35
Use the reddit suggestion where all player data is anonymous until the strategy phase is over.  Overwolf is cancer in the drafting phase and should be eliminated.  A lot of us would like our match data to be available for learning purposes, but also not be ban sniped in the drafting phase.

**Comment by deanrih** [comment] 2022-06-11 17:19
I understand the sentiment, whether this tool is a cheat or not, but please don't post or submit this here, this is Dota 2 **BUG TRACKER**, please, before some of you post reasonable discussion just look at the submission content first, is it a BUG or NOT? If it is not, then please "downvote" this, yes this might increase the visibility of the "problem" but doesn't that mean Valve will act upon it, in fact, if they read this it will be just closed because it is out of scope and not the purpose of this public repository.

Just when we get the proper way to submit a bug, it somehow always being ruined by the out-of-scope or unrelated report, and you wonder why Valve took so long to fix something or rarely communicates at all.

So for that, Close this Issue and post it back on Reddit, not that we, as a player don't care about whether the tools make the game unbalanced or not, it's just this submission just dirtied up this repository from the actual bug reports.

**Comment by maakep** [comment] 2022-06-11 19:26
#897 describes the unintended, arguably buggy, behaviour & proposed solution.

**Comment by SenorRagequit** [comment] 2022-06-13 10:38
How can you > not < call this a cheat ? It gives you a mile high advantage over your enemies as you could never gather that data in such a short time yourself. 
Might as well allow it in TI when it's nothing bad. The only people who don't call this a cheat are people who use it.
This crap should be banned, but at the root like disabling player ids up until the game loads into the map or w/e

**Comment by Memoframe** [comment] 2022-06-13 10:54
> How can you > not < call this a cheat ? It gives you a mile high advantage over your enemies as you could never gather that data in such a short time yourself. Might as well allow it in TI when it's nothing bad. The only people who don't call this a cheat are people who use it. This crap should be banned, but at the root like disabling player ids up until the game loads into the map or w/e

At TI teams know all info about opponents, they do not need it.

**Comment by maakep** [comment] 2022-06-13 11:26
> At TI teams know all info about opponents, they do not need it.

Not at all correct, at tournaments software like this would be illegal. That's why they have papers prepared, pre-work with computers but still in the heat of the moment - you rely on yourselves and your core prep-work. A computer is "infinite" and automatic and can react to any change. The enemy team pulls out a pocket specialized draft never seen before & you're totally unprepared for it? Whatever, computer counters it.

Because having a computer tell you the optimal draft is cheating. It's the computer competing instead of you. If you can have a computer react to the draft, why not let the computer react to the gameplay too? Analyzing drafts are also completely publicly open for anyone to do, just like drafts. Just analyze the patters of the enemy player so you can get information on how they move and where they ward etc. Show overlays on where to deward, when to rotate, what farming patters the enemy carry does. How is that different? I'd say countering the draft is more impactful than this.

---- 

I don't think there is any question to whether or not Overwolf should be disallowed, I have a hard time believing even people who uses it deep down feels like it's a fair, just & honorable tool. I'm guessing people are defending it for copium reasons; they perceive that it helps the get MMR which is more important that having a fair & fun platform - or just enjoying the unfair advantage they get and turns a blind eye to the morality of it.

"You can just turn off data sharing" is a frequent, faulty, argument. People want to be able to expose their data, to be used in analytical tools and online reviewing of their games. It's fun, valuable and all-around great. Getting automatically parsed for optimal counters to your likely draft in runtime is NOT a good look.

----

@deanrih 

> I understand the sentiment, whether this tool is a cheat or not, but please don't post or submit this here, this is Dota 2 BUG TRACKER

This could be phrased as a bug though; that allows hacks (Overwolf is a hack in the same way reading the game for other data and automatically present it to the player in order to help their game is) to be created, as they leak personal details to the client files. I do agree though, I feel like this is not the purpose of the tracker but the setup should be resillient and able to have these kinds of discussions too.

**Comment by deanrih** [comment] 2022-06-13 11:52
> 
> @deanrih 
> 
> > I understand the sentiment, whether this tool is a cheat or not, but please don't post or submit this here, this is Dota 2 BUG TRACKER
> 
> This could be phrased as a bug though; that allows hacks (Overwolf is a hack in the same way reading the game for other data and automatically present it to the player in order to help their game is) to be created, as they leak personal details to the client files. I do agree though, I feel like this is not the purpose of the tracker but the setup should be resillient and able to have these kinds of discussions too. 




This "functionality" has existed for a long time also with something similar like GSI (Game State Integration, that used on every major tournament, and I know, practically it is different) so wether or not it actually a bug is up to Valve, but the point here maybe is shifting the problem or issues to the Dota 2 itself instead of the 3rd party, let's say yes it was a bug, then frame it as Dota 2 bug with an example of leaked info on log file or what not, not focusing on something like overwolf even if it utilise this bug

**Comment by Memoframe** [comment] 2022-06-13 11:53
> > At TI teams know all info about opponents, they do not need it.
> 
> Not at all correct, at tournaments software like this would be illegal. That's why they have papers prepared and aren't allowed third-party software during games & drafts. Pre-work with computers is still done, most likely, but in the moment of competition - you rely on yourselves and your core prep-work. A computer is "infinite" and automatic and can react to any change. The enemy team pulls out a pocket specialized draft never seen before & you're totally unprepared for it? Whatever, computer counters it.

But they use public api (dotabuff of custom scripts) to fill that papers and that papers have 100 times more info than you ever will have from overwolf, so for them it's useless.
Also it's a fair point about acc boosters over here too, lose to rank 1000 Arc is more painful than do not play one of your fav heroes.
My 5 cents will be not block data at start but showing same info OW does to all players.
It will level everyone and tone down boosters a bit as well.

**Comment by jeffhill** [comment] 2022-06-14 19:45
I'm sorry, but this issue is out of scope for the bug tracker. Thank you for sharing your thoughts here!

**Closed by jeffhill** 2022-06-14 19:45 UTC

**Comment by cyrilmir** [comment] 2023-08-11 14:22
why do you allow open API.  Hackers use it to take advantage and manipulate gameplay on a mass scale.  Its RUINING the game.
