### ISSUE TITLE
Some Arcanas still use default hero chat wheels

### ISSUE THREAD

**Issue by ZharDar** [jeffhill/Dota2#562] opened 2022-06-04 17:36 UTC
### Cosmetic Item Name

Tempest Helm of the Thundergod, Blades of Voth Domosh, etc

### Description

Some hero arcanas (namely lc arcana, pudge arcana, zeus arcana, monkey king, etc) use the default hero chat wheel lines even when the arcana is equipped. They do not use pitch shifted lines like the Juggernaut arcana does (even without his voice pack, the lines are pitch-shifted and edited).

### Example Match ID

N/A

**Comment by BenjinZA** [comment] 2022-06-04 18:18
Duplicate of #93

**Closed** 2022-06-04 18:31 UTC
