### ISSUE TITLE
MVP does not show for non-standard game modes

### ISSUE THREAD

**Issue by Daar543** [jeffhill/Dota2#1001] opened 2022-06-10 01:21 UTC
### Description

- Problem: MVP seems to show only for All Pick; For Single Draft (no LP) and Ability draft does MVP not show, did not check other game modes

- Suggestion: Make MVP track Single Draft and All Random as if they were normal All Pick game mode. For Ability draft, count usages of any ability the hero has.

### Example Match ID (and possibly Timestamp)

All matches fromm Single draft and Ability Draft

_No response_

**Comment by RGBKnights** [comment] 2022-06-10 17:09
This is a duplicate of #253. Please close this issue.
You can search for open AD tickets with the following [link](https://github.com/jeffhill/Dota2/issues?page=1&q=is%3Aissue+is%3Aopen+Ability+Draft)

**Comment by Daar543** [comment] 2022-06-11 23:43
Closing then

**Closed** 2022-06-11 23:43 UTC
