### ISSUE TITLE
Epicenter sound queue bug

### ISSUE THREAD

**Issue by peachlaugh** [jeffhill/Dota2#405] opened 2022-06-03 14:19 UTC
### Ability name

Epicenter

### Description

When pressing Epicenter and cancel it mid-channel, there's a fake ult sound queue even if not fully activated. Teammates can hear the fake ult sound queue so they are confused and get baited.

Match ID and timestamp:
So what happened in the clip is Sand King tries to ult and cancels it multiple times so the Undying got baited and thought that the Epicenter is popped so he blinked in and die.

### Example Match ID (and possibly Timestamp)

6599710656 - 35:42

**Comment by Uwila** [comment] 2022-06-03 16:40
Duplicate of #343 , please close this issue.

**Closed** 2022-06-06 09:50 UTC
